SELECT
    ITE.NUNOTA      AS NUNOTARET,
    ITE.SEQUENCIA   AS SEQUENCIARET,
    ITE.CODPROD,
    ITE.VLRUNIT,
    ITE.CODVOL,
    ITE.AD_QTDDEVOL AS QTDNEG,
    ITE.CONTROLE,
    ITE.CODLOCALORIG
FROM TGFITE ITE
WHERE ITE.NUNOTA = :NUNOTA
  AND NVL(ITE.AD_QTDDEVOL, 0) > 0