SELECT
    ITE.CODPROD,
    ITE.CODVOL,
    ITE.CONTROLE,
    SUM(CASE WHEN VOA.DIVIDEMULTIPLICA = 'M' THEN ITE.QTDNEG/VOA.QUANTIDADE
             WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN ITE.QTDNEG*VOA.QUANTIDADE
              ELSE (ITE.QTDNEG-ITE.QTDENTREGUE) END
        ) QTDNEG
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TGFVOA VOA ON VOA.CODPROD = ITE.CODPROD AND VOA.CODVOL = ITE.CODVOL
WHERE CAB.CODTIPOPER = 129
  AND CAB.AD_IDIPROC = :IDIPROC
GROUP BY
    ITE.CODPROD,
    ITE.CODVOL,
    ITE.CONTROLE