WITH OP AS (
    SELECT
        ATV.IDIATV,
        ATV.IDIPROC,
        UPPER(TRIM(EFX.DESCRICAO)) AS DESCR_ATIV,
        MAX(CAB.NUNOTA) AS NUNOTA,
        MIN(PRO.DESCRPROD) AS DESCRPROD,
        SUM(NVL(IPA.QTDPRODUZIR, 0)) AS QTDPRODUZIR
    FROM TPRIATV ATV
    LEFT JOIN TGFCAB CAB ON ATV.IDIPROC = CAB.AD_IDIPROC
    LEFT JOIN TPRIPA IPA ON ATV.IDIPROC = IPA.IDIPROC
    LEFT JOIN TGFPRO PRO ON IPA.CODPRODPA = PRO.CODPROD
    LEFT JOIN TPREFX EFX ON ATV.IDEFX = EFX.IDEFX
    WHERE ATV.IDIATV = :IDIATV
    GROUP BY ATV.IDIATV, ATV.IDIPROC, UPPER(TRIM(EFX.DESCRICAO))
),
MAPEAMENTO AS (
    SELECT
        OP.*,
        CASE
            /* MECÂNICA */
            WHEN OP.DESCR_ATIV IN ('CORTE', 'DOBRA', 'SOLDA', 'PINTURA', 'MONTAGEM MECANICA', 'MONTAGEM MECÂNICA')
                THEN 8  /* CODGRUPO MECANICA */

            /* ENGENHARIA */
            WHEN OP.DESCR_ATIV IN ('PROJETO ELÉTRICO', 'PROJETO ELETRICO', 'PROJETO MECÂNICO', 'PROJETO MECANICO', 'MONTAGEM ELÉTRICA', 'MONTAGEM ELETRICA')
                THEN 6  /* CODGRUPO ENGENHARIA */

            /* ASTEC / TAF */
            WHEN OP.DESCR_ATIV IN ('TAF')
                THEN 10 /* CODGRUPO ASTEC */

            /* SGI / INSPEÇÃO */
            WHEN OP.DESCR_ATIV IN ('INSPEÇÃO', 'INSPECAO')
                THEN 11 /* CODGRUPO GRUPO SGI */

            ELSE NULL
        END AS CODGRUPO
    FROM OP
)
SELECT
    M.IDIATV,
    M.IDIPROC,
    M.DESCR_ATIV AS DESCRICAO,
    M.NUNOTA,
    M.DESCRPROD,
    M.QTDPRODUZIR,
    GRU.NOMEGRUPO AS NOMEUSU,
    REGEXP_REPLACE(GRU.EMAIL, '[[:space:]]', '') AS EMAIL
FROM MAPEAMENTO M
LEFT JOIN TSIGRU GRU
    ON GRU.CODGRUPO = M.CODGRUPO
WHERE M.CODGRUPO IS NOT NULL
  AND GRU.EMAIL IS NOT NULL
  AND LENGTH(REGEXP_REPLACE(GRU.EMAIL, '[[:space:]]', '')) > 0
  AND INSTR(REGEXP_REPLACE(GRU.EMAIL, '[[:space:]]', ''), '@') > 1