CREATE OR REPLACE VIEW AD_VWBHZIMRP  AS
WITH ESTOQUE AS (SELECT
	     CODPROD
		,CODEMP
		,SUM(ESTOQUE - RESERVADO) AS QTDNEG
	FROM TGFEST

INNER JOIN
    TGFLOC
        ON TGFEST.CODLOCAL= TGFLOC.CODLOCAL
	WHERE  NVL(TGFLOC.AD_ESTUTIL,
    'N') = 'S'
	GROUP
BY
    CODPROD,
    CODEMP)

,
    PEDIDO AS (
		SELECT
		     TGFITE.CODPROD
			,
    TGFCAB.CODEMP
			,
    SUM(TGFITE.QTDNEG-TGFITE.QTDENTREGUE) AS QTDNEG
			,
    NVL(TGFITE.DTINICIO,
    TGFCAB.DTPREVENT) AS DTPREV
		FROM TGFITE
		INNER
JOIN
    TGFCAB
        ON TGFITE.NUNOTA = TGFCAB.NUNOTA
		INNER
JOIN
    TGFTOP
        ON TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
        AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
		WHERE TGFCAB.TIPMOV = 'O'

        AND TGFCAB.PENDENTE = 'S'

        AND TGFTOP.AD_TIPOANALISE = 'C'

        AND TGFCAB.STATUSNOTA = 'L'
		GROUP
BY
    TGFITE.    CODPROD
			,
    TGFCAB.CODEMP
			,
    NVL(TGFITE.DTINICIO,
    TGFCAB.DTPREVENT))

,
    CONSUMO AS (
        SELECT
            MPS.NUMPS,

            CAB.CODEMP,

            ITE.CODPROD,

            SUM(ITE.QTDNEG) QTDNEG

FROM
    TGFCAB CAB

INNER JOIN
    TGFITE ITE
        ON CAB.NUNOTA = ITE.NUNOTA

        AND ITE.ATUALESTOQUE = -1

INNER JOIN
    TPRIPROC IPROC
        ON IPROC.IDIPROC = CAB.IDIPROC

INNER JOIN
    TPRMPS MPS
        ON (NVL(IPROC.NUMPS,
    0) = MPS.NUMPS
    OR (NVL(IPROC.NUMPS,
    0)  = 0
    AND CAB.DTNEG BETWEEN MPS.DTINICMPS AND MPS.DTFINMPS))

WHERE
    CAB.TIPMOV = 'F'

GROUP BY
            CAB.CODEMP,
            ITE.CODPROD,
            MPS.NUMPS
),
BHZ_RECEITA AS (
    SELECT
        PLP.CODEMP,
        LMP.CODPRODPA CODPRODPAPAI,
        LMP.CODPRODPA,
        LMP.CODPRODMP,
        CASE
    WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN LMP.QTDMISTURA/VOA.QUANTIDADE

    WHEN VOA.DIVIDEMULTIPLICA = 'M' THEN LMP.QTDMISTURA*VOA.QUANTIDADE

    ELSE LMP.QTDMISTURA
END QTD,
        CASE
    WHEN LPI.CODPRODPA IS NULL THEN 'MP'
    ELSE 'PI'
END TIPO
    FROM
    TPRLPA LPA

INNER JOIN
    TPRPRC PRC
        ON PRC.IDPROC = LPA.IDPROC
        AND PRC.IDPROC = (SELECT
            MAX(IDPROC)
    FROM
        TPRPRC
    WHERE
        CODPRC = PRC.CODPRC)

INNER JOIN
    TPRPLP PLP
        ON PLP.CODPLP = PRC.CODPLP

INNER JOIN
    TPRLMP LMP
        ON LMP.CODPRODPA = LPA.CODPRODPA

INNER JOIN
    TGFPRO PRO
        ON PRO.CODPROD = LMP.CODPRODMP

LEFT JOIN
    TGFVOA VOA
        ON VOA.CODPROD = PRO.CODPROD
        AND VOA.CODVOL = LMP.CODVOL

INNER JOIN
    TPRATV ATV
        ON LMP.IDEFX = ATV.IDEFX
        AND PRC.IDPROC = ATV.IDPROC

LEFT JOIN
    TPRLPI LPI
        ON LPI.CODPRODPA = LPA.CODPRODPA
        AND LPI.CODPRODPI = LMP.CODPRODMP
        AND LPI.IDPROC = PRC.IDPROC

WHERE
    NVL(LPA.AD_RECEITACONSOLIDADA,'N') = 'N'

    AND NVL(PRC.PROCDESMONTE,'N') = 'N'

ORDER BY
    LPA.CODPRODPA
),

PLANEJAMENTO AS (
        SELECT
            'M' TIPO,

            LMP.CODPRODMP,

            LMP.CODEMP,

            MPS.DTINICMPS DTPREV,

            0 IDIPROC,

            MPS.NUMPS,

            MPS.DTINICMPS,

            MPS.DTFINMPS,

            0 NUPED,

            SUM(IMPS.QTDPRODUZIRLIQ*LMP.QTD) QTD,

            1 SEQUENCIA,

            MPS.DTINICMPS  SEQ,

            MPS.CODUSU,

            SUM(NVL(CONSUMO.QTDNEG,
    0)) QTDCONSUMIDO,

            CASE
        WHEN SUM(NVL(CONSUMO.QTDNEG,
        0)) >= SUM(IMPS.QTDPRODUZIRLIQ*LMP.QTD)
                             THEN 0

        ELSE SUM(IMPS.QTDPRODUZIRLIQ*LMP.QTD)-SUM(NVL(CONSUMO.QTDNEG,
        0))
    END QTDSALDO

FROM
    TPRMPS MPS

INNER JOIN
    TPRIMPS IMPS
        ON IMPS.NUMPS = MPS.NUMPS

INNER JOIN
    TPRPRC PRC
        ON PRC.IDPROC = IMPS.IDPROC

INNER JOIN
    TPRPLP PLP
        ON PLP.CODPLP = MPS.CODPLANTA

INNER JOIN
    BHZ_RECEITA LMP
        ON LMP.CODPRODPAPAI = IMPS.CODPROD

LEFT JOIN
    CONSUMO
        ON CONSUMO.CODEMP = LMP.CODEMP

        AND CONSUMO.CODPROD = LMP.CODPRODMP

        AND CONSUMO.NUMPS = MPS.NUMPS

WHERE
    MPS.CODCMPS IN (7)

    AND MPS.SITUACAO = 'P'

    AND IMPS.QTDPRODUZIRLIQ > 0

    AND IMPS.PRODINTERM = 'N'

GROUP BY
            LMP.CODPRODMP,
            LMP.CODEMP,
            MPS.DTINICMPS,
            MPS.NUMPS,
            MPS.DTINICMPS,
            MPS.DTFINMPS,
            MPS.CODUSU)
,ESTMIN AS (
SELECT
    'E' TIPO,
    PRO.CODPROD CODPRODMP,
    1 CODEMP,
    SYSDATE DTPREV,
    0 IDIPROC,
    0 NUMPS,
    SYSDATE DTINICMPS,
    SYSDATE DTFINMPS,
    0 NUPED,
    CASE
        WHEN NVL(ESTOQUE.QTDNEG,0) < NVL(PRO.ESTMIN,0) THEN NVL(PRO.ESTMIN,0)-NVL(ESTOQUE.QTDNEG,0)
        ELSE 0
    END QTD,
    2 SEQUENCIA,
    SYSDATE  SEQ,
    0 CODUSU,
    0 QTDCONSUMIDO,
    CASE
    WHEN NVL(ESTOQUE.QTDNEG,0) < NVL(PRO.ESTMIN,0) THEN NVL(PRO.ESTMIN,0)-NVL(ESTOQUE.QTDNEG,0)
    ELSE 0
END QTDSALDO
FROM TGFPRO PRO
LEFT JOIN
    ESTOQUE
        ON PRO.CODPROD = ESTOQUE.CODPROD
        AND CASE
            WHEN NVL(ESTOQUE.QTDNEG, 0) < NVL(PRO.ESTMIN, 0)
            THEN NVL(ESTOQUE.QTDNEG, 0) - NVL(PRO.ESTMIN, 0)
        ELSE 0
    END > 0
WHERE PRO.CODPROD NOT IN (SELECT
        CODPRODMP
    FROM
        PLANEJAMENTO)

    AND NVL(PRO.ESTMIN,
    0)> 0)
,

SOLICITACAO AS (
SELECT
    'S' TIPO,

    TGFITE.CODPROD CODPRODMP,

    1 CODEMP,

    NVL(TGFCAB.DTPREVENT,
    TGFCAB.DTNEG) DTPREV,

    0 IDIPROC,

    TGFCAB.NUNOTA NUMPS,

    NVL(TGFCAB.DTPREVENT,
    TGFCAB.DTNEG) DTINICMPS,

    NVL(TGFCAB.DTPREVENT,
    TGFCAB.DTNEG) DTFINMPS,

    0 NUPED,

    (NVL(TGFITE.QTDNEG,
    0) - NVL(TGFITE.QTDENTREGUE,
    0)) QTD,

    TGFITE.SEQUENCIA+3 SEQUENCIA,

    NVL(TGFCAB.DTPREVENT,
    TGFCAB.DTNEG)  SEQ,

    TGFCAB.CODUSUINC CODUSU,

    0 QTDCONSUMIDO,

    (NVL(TGFITE.QTDNEG,
    0) - NVL(TGFITE.QTDENTREGUE,
    0)) QTDSALDO

FROM
    TGFITE

INNER JOIN
    TGFCAB
        ON TGFITE.NUNOTA = TGFCAB.NUNOTA

INNER JOIN
    TGFTOP
        ON TGFTOP.CODTIPOPER = TGFCAB.CODTIPOPER

        AND TGFTOP.DHALTER = TGFCAB.DHTIPOPER

LEFT JOIN
    TGFVAR VAR
        ON VAR.NUNOTAORIG = TGFCAB.NUNOTA

        AND VAR.SEQUENCIAORIG = TGFITE.SEQUENCIA

LEFT JOIN
    TGFITE IPED
        ON VAR.NUNOTA = IPED.NUNOTA

        AND VAR.SEQUENCIA = IPED.SEQUENCIA

LEFT JOIN
    TGFCAB PED
        ON VAR.NUNOTA = PED.NUNOTA

        AND PED.STATUSNOTA = 'L'

WHERE
    (NVL(TGFITE.QTDNEG, 0) - NVL(IPED.QTDNEG, 0)) > 0

    AND TGFCAB.CODTIPOPER = 78 --SOLICITAÇÃO DE COMPRA

    AND TGFCAB.PENDENTE = 'S'

    AND TGFCAB.DTNEG >= '01/01/2026'

    AND TGFCAB.STATUSNOTA = 'L')
,PLANO AS (
SELECT *
FROM
    PLANEJAMENTO
UNION ALL
SELECT *
FROM
    ESTMIN
UNION ALL
SELECT *
FROM
    SOLICITACAO)
,
    T1 AS (SELECT
        PLANO.TIPO
            ,
        PLANO.CODEMP
			,
        GRU.CODGRUPOPROD
			,
        GRU.CODGRUPAI
			,
        NVL(PAR.CODPARC,
        0) CODPARC
			,
        PLANO.CODPRODMP
			,
        ' ' CONTROLEMP
    		,
        PLANO.DTPREV
			,
        NVL(PRO.LEADTIME,
        0) LEADTIME
			,
        PLANO.DTPREV - NVL(PRO.LEADTIME ,
        0) - 1 LIMITECOMPRA
			,
        PLANO.IDIPROC
			,
        PLANO.NUMPS
			,
        PLANO.NUPED
			,
        PLANO.QTD
			,
        PLANO.SEQUENCIA
			,
        PLANO.QTDCONSUMIDO
			,
        SUM(NVL(PED.QTDNEG,
        0)) QTDPEND
			,
        NVL(EST.QTDNEG,
        0) QTDEST
			,
        0 ACUMULADO
			,
        PRO.USOPROD
			,
        NVL(PRO.ESTMIN,
        0) ESTMIN
			,
        NVL(PRO.ESTMAX,
        0) ESTMAX
			,
        NVL(PRO.AGRUPMIN,
        0) QTDAGRUP
            ,
        NVL(PRO.AGRUPCOMPMINIMO,
        0) AGRUPCOMPMINIMO
			,
        PLANO.CODUSU
			,
        PRO.CODPROD
		FROM PLANO
		INNER
    JOIN
        TGFPRO PRO
            ON PRO.CODPROD = PLANO.CODPRODMP
		INNER
    JOIN
        TGFGRU GRU
            ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
		LEFT
    JOIN
        TGFPAR PAR
            ON PAR.CODPARC = PRO.CODPARCFORN
		LEFT
    JOIN
        ESTOQUE EST
            ON EST.CODPROD = PRO.CODPROD
            AND EST.CODEMP = PLANO.CODEMP
		LEFT
    JOIN
        PEDIDO PED
            ON PED.DTPREV <= PLANO.DTPREV
            AND PED.CODPROD = PRO.CODPROD
		--
    LEFT JOIN
        PEDIDO PED
            ON PED.CODPROD = PRO.CODPROD
		WHERE NVL(PLANO.QTD,
        0) > 0
		GROUP BY
		     PLANO.TIPO
		    ,
        PLANO.CODEMP
			,
        GRU.CODGRUPOPROD
			,
        GRU.CODGRUPAI
			,
        NVL(PAR.CODPARC,
        0)
			,
        PLANO.CODPRODMP
    		,
        PLANO.DTPREV
			,
        NVL(PRO.LEADTIME,
        0)
			,
        PLANO.DTPREV
			,
        PLANO.IDIPROC
			,
        PLANO.NUMPS
			,
        PLANO.NUPED
			,
        PLANO.QTD
			,
        PLANO.SEQUENCIA
			,
        PLANO.QTDCONSUMIDO
			,
        NVL(EST.QTDNEG,
        0)
			,
        PRO.USOPROD
			,
        NVL(PRO.ESTMIN,
        0)
			,
        NVL(PRO.ESTMAX,
        0)
			,
        NVL(PRO.AGRUPMIN,
        0)
            ,
        NVL(PRO.AGRUPCOMPMINIMO,
        0)
			,
        PLANO.CODUSU
			,
        PRO.CODPROD)

SELECT
     TIPO
	,
    CODGRUPOPROD
	,
    CODPARC
	,
    CODEMP
	,
    CODPRODMP
	,
    CONTROLEMP
	,
    DTPREV DTINI
	,
    LEADTIME
	,
    LIMITECOMPRA
	,
    0 IDIPROC
	,
    NUMPS
	,
    NUPED
	,
    QTD QTDNEG
	,
    SEQUENCIA SEQIMRP
	,
    QTDCONSUMIDO
	,
    QTDPEND
	,
    QTDEST
	,
    0 SUGERIDO
	,
    0 ACUMULADO
	,
    USOPROD
	,
    ESTMIN
	,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM TGFGRU G
            WHERE G.CODGRUPOPROD = T1.CODGRUPAI
        ) THEN T1.CODGRUPAI
        ELSE NULL
    END AS CODGRUPAI
	,
    ESTMAX
	,
    QTDAGRUP
    ,
    AGRUPCOMPMINIMO
	,
    CODUSU
FROM T1