SELECT CASE WHEN SNK_PRECO(:CODTAB,:CODPROD) > 0 THEN SNK_PRECO(:CODTAB,:CODPROD)
       ELSE  CUSREP END CUSREP
FROM TGFCUS C
WHERE CODPROD = :CODPROD
  AND DTATUAL = (SELECT MAX(DTATUAL)
                   FROM TGFCUS
                  WHERE CODPROD = C.CODPROD
                    AND DTATUAL <= SYSDATE AND CUSREP > 0)
 AND CUSREP > 0