INSERT INTO AD_BHZIMRP ( ORDEM
                        ,TIPO
                        ,CODGRUPOPROD
                        ,CODPARC
                        ,CODEMP
                        ,CODPRODMP
                        ,CONTROLEMP
                        ,DTINI
                        ,LEADTIME
                        ,LIMITECOMPRA
                        ,IDIPROC
                        ,NUMPS
                        ,NUPED
                        ,QTDNEG
                        ,SEQIMRP
                        ,QTDPEND
                        ,QTDEST
                        ,ESTOQUE
                        ,RESERVA
                        ,SUGERIDO
                        ,ACUMULADO
                        ,USOPROD
                        ,ESTMIN
                        ,CODGRUPAI
                        ,ESTMAX
                        ,QTDAGRUP
                        ,CODUSU
                        ,AGRUPCOMPMINIMO
                        ,REFFORN
                        ,REFERENCIA
                        ,VENDA_3M
                        ,VENDA_6M
                        ,ULTIMA_VENDA
                        ,ULTIMO_CUSGER)
SELECT ORDEM
    ,TIPO
    ,CODGRUPOPROD
    ,CODPARC
    ,CODEMP
    ,CODPRODMP
    ,CONTROLEMP
    ,DTINI
    ,LEADTIME
    ,LIMITECOMPRA
    ,IDIPROC
    ,NUMPS
    ,NUPED
    ,QTDNEG
    ,SEQIMRP
    ,QTDPEND
    ,QTDEST
    ,ESTOQUE
    ,RESERVA
    ,SUGERIDO
    ,ACUMULADO
    ,USOPROD
    ,ESTMIN
    ,CODGRUPAI
    ,ESTMAX
    ,QTDAGRUP
    ,CODUSU
    ,AGRUPCOMPMINIMO
    ,REFFORN
    ,REFERENCIA
    ,VENDA_3M
    ,VENDA_6M
    ,ULTIMA_VENDA
    ,ULTIMO_CUSGER
FROM AD_VWBHZIMRP
ORDER BY ORDEM
