INSERT INTO AD_BHZIMRP (TIPO
                        ,CODGRUPOPROD
                        ,CODPARC
                        ,CODEMP
                        ,CODPRODMP
                        ,CONTROLEMP
                        ,DTINI
                        ,LEADTIME
                        ,LIMITECOMPRA
                        ,IDIPROC
                        ,NUMPS
                        ,NUPED
                        ,QTDNEG
                        ,SEQIMRP
                        ,QTDPEND
                        ,QTDEST
                        ,SUGERIDO
                        ,ACUMULADO
                        ,USOPROD
                        ,ESTMIN
                        ,CODGRUPAI
                        ,ESTMAX
                        ,QTDAGRUP
                        ,CODUSU
                        ,AGRUPCOMPMINIMO)
SELECT TIPO
    ,CODGRUPOPROD
    ,CODPARC
    ,CODEMP
    ,CODPRODMP
    ,CONTROLEMP
    ,DTINI
    ,LEADTIME
    ,LIMITECOMPRA
    ,IDIPROC
    ,NUMPS
    ,NUPED
    ,QTDNEG
    ,SEQIMRP
    ,QTDPEND
    ,QTDEST
    ,SUGERIDO
    ,ACUMULADO
    ,USOPROD
    ,ESTMIN
    ,CODGRUPAI
    ,ESTMAX
    ,QTDAGRUP
    ,CODUSU
    ,AGRUPCOMPMINIMO
FROM AD_VWBHZIMRP
ORDER BY CODEMP,CODPRODMP,LIMITECOMPRA