UPDATE AD_BHZIMRP
SET ACUMULADO = :ACUMULADO
   ,SUGERIDO = :SUGERIDO
   ,QTDEST = :QTDEST
   ,QTDPEND = :QTDPEND
WHERE CODPRODMP = :CODPRODMP
  AND CODEMP = :CODEMP
  AND NUMPS = :NUMPS
  AND DTINI = :DTINI